### ISSUE TITLE
Make Threshold for takeAction fire a configurable variable?

### ISSUE THREAD

**Issue by quadrophobiac** [lmccart/Social-Hacking-Workshop#1]
When using the app it was necessary to open the console to determine why MakerChannel triggers weren't firing.
It seemed like a given emotion from available ranges needed to exceed 90% in order for `takeAction()` function to take effect.
Uncertain if this is intended behaviour - totally understand if this is a decision relating to the workshop in which this featured, or if its the best solution to the CV tech this app uses.
BUT it would be great to make this threshold configurable. In my experience this threshold meant that the application couldn't be run as indicated on the website:

>  leave the browser window running for at least 30 minutes while working on other things and let your recipe(s) run

Unless I was actively forcing facial expressions to exceed the threshold nothing was firing into IFTTT.

Really like this app and I think it's an excellent intersection of passive lifelogging tech with biometric tech critiques. Love the continuity with People Staring at Computers. My interest is mainly in using it as a way of letting students (and perhaps staff at the ODI) generate interesting data for use with other integrations that IFTTT affords

**Comment by kylemcdonald** [comment]
hey! we're happy to accept carefully tested and submitted PRs but won't be working on this repo until we do this workshop again.

and yes, 90% was our tradeoff between firing too much and too little. yes, for some faces, in some lighting conditions, 90% will be too much or too little.
